# Generated by Django 6.0 on 2025-12-22 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('is_free', models.BooleanField(default=False, verbose_name='Бесплатный')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность')),
                ('difficulty', models.CharField(choices=[('hard', 'Сложный'), ('medium', 'Средний'), ('easy', 'Легкий'), ('unknown', 'Не задан')], default='unknown', max_length=64, verbose_name='Сложность')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_courses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'db_table': 'course',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CourseTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название темы')),
                ('order', models.PositiveIntegerField(help_text='Используется для корректного отображения тем на фронте', verbose_name='Порядковый номер')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалена')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='api.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Тема курса',
                'verbose_name_plural': 'Темы курса',
                'db_table': 'course_theme',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ThemeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('title', 'Заголовок'), ('text', 'Текст'), ('image', 'Изображение')], default='text', max_length=32, verbose_name='Тип блока')),
                ('title', models.CharField(blank=True, help_text="Используется для блоков типа 'Заголовок'", max_length=256, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, help_text='Используется для текстовых блоков', null=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, help_text='Используется для блоков с изображением', null=True, upload_to='course/theme_blocks/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(verbose_name='Порядковый номер')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='api.coursetheme', verbose_name='Тема курса')),
            ],
            options={
                'verbose_name': 'Блок темы',
                'verbose_name_plural': 'Блоки темы',
                'db_table': 'theme_block',
                'ordering': ('order',),
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['name'], name='course_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_course_name'),
        ),
        migrations.AddIndex(
            model_name='coursetheme',
            index=models.Index(fields=['course', 'order'], name='course_theme_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursetheme',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='unique_theme_order_per_course'),
        ),
        migrations.AddIndex(
            model_name='themeblock',
            index=models.Index(fields=['theme', 'order'], name='theme_block_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='themeblock',
            constraint=models.UniqueConstraint(fields=('theme', 'order'), name='unique_block_order_per_theme'),
        ),
    ]
